# Generated by Django 5.1.7 on 2025-03-31 11:41

import photo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_code', models.CharField(default=photo.models.default_time_code, max_length=12)),
                ('image_file', models.ImageField(upload_to=photo.models.image_upload_path)),
            ],
        ),
    ]
