# Generated by Django 5.1.7 on 2025-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_add_place_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='executor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='task_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
