# Generated by Django 5.1.7 on 2025-03-27 14:27

import audiorecord.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('time_code', models.CharField(default=audiorecord.models.default_time_code, max_length=12, verbose_name='时间代码')),
                ('audio_file', models.FileField(upload_to=audiorecord.models.audio_upload_path, verbose_name='语音文件')),

            ],
        ),
    ]
