# Generated by Django 5.1.7 on 2025-03-31 11:34

import audiorecord.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiorecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to=audiorecord.models.audio_upload_path),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='time_code',
            field=models.CharField(default=audiorecord.models.default_time_code, max_length=12),
        ),
    ]
