# Generated by Django 5.1.6 on 2025-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studydjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='M', max_length=100),
            preserve_default=False,
        ),
    ]
